### PR TITLE
Test propagation for tracing

### PR DESCRIPTION
**Pull request by yasmin-aumeeruddy**
Tests the use of different propagation formats, including that the right headers are set

For isse #89

### CODE REVIEW

**Review by pdudits — APPROVED** [review]
~~Looks good and works for us~~ Sorry missed the console output that it didn't build. Apparently it builds on top of #95, I'll try this later

**Comment by Azquelt** [comment]
> I'm not convinced the specification requires propagators that are not part of core distribution to be available out of the box.

I think we should clarify this in the spec. Currently we link to the page for [SDK Autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/v1.19.0/sdk-extensions/autoconfigure) and say that all properties related to tracing are supported, and that includes options for jaeger and B3.

If we only expect the propagators from the core distribution to be present, we need to state that in the spec. Similarly if we expect users to be able to provide them themselves, we should test that too (to ensure that any runtimes which do provide them out of the box don't fail if they're also provided in the application).

**Comment by pdudits** [comment]
Yes, with regards I was thinking about enumerating the properties in the spec. This would help us being independent from alpha-state of SDK autoconfigure  as well as being flexible in which version of SDK is actually available in an implementation.

I'll try to make a spec PR regarding that

**Comment by pdudits** [comment]
#103 attempts to clarify minimal requirements for propagators, as well as exporters and samplers.

**Comment by Emily-Jiang** [comment]
@yasmin-aumeeruddy please fix the build errors.

**Review by Emily-Jiang — APPROVED** [review]

**Pull request merged**
