### PR TITLE
bump OpenTelemetry Java Version to 1.19.0 including TCK and README updates

### PR DESCRIPTION
**Pull request by JanWesterkamp-iJUG**
Here is the updated PR with updated opentelemetry-java-instrumentation, updated TCK, updated README and NOTICE files etc.

@Emily-Jiang, @brunobat and @radcortez, I also added a rudimentary README.adoc for the TCK, but this still needs some work to be done.

### CODE REVIEW

**Comment by JanWesterkamp-iJUG** [comment]
> I'd prefer all the unrelated documentation updates done in an independent PR. Rebase needed

I will do a rebase of the original PR https://github.com/eclipse/microprofile-telemetry/pull/60 first, that was focusing on the spec doc update. But then @Emily-Jiang and you need to decide if I should do separate PRs for the doc and code or not for the rest of the changes.

This 2nd part will be done afterwards, within the 1st one, on a new one or a few new ones dependeing on your consensus.

**Comment by brunobat** [comment]
@JanWesterkamp-iJUG it's not about separating code and docs. It's about having PRs that match the PR title. 
This is called "Otel java version update 2"and there are a bunch of documentation changes including how to run the TCK. 
No need to split this. Just mind in the future.

**Comment by JanWesterkamp-iJUG** [comment]
> @JanWesterkamp-iJUG it's not about separating code and docs. It's about having PRs that match the PR title. This is called "Otel java version update 2"and there are a bunch of documentation changes including how to run the TCK. No need to split this. Just mind in the future.

Oh ok, it was intendend to be an update to the exisiting PR [bump OpenTelemetry specification version to 1.14.0 including refinements](https://github.com/eclipse/microprofile-telemetry/pull/60), but it was late and it looks like I forgot to change the name the PR, as the branch name was not enough.

Of couse that name is not fitting to this changes anymore too, because of the requests in that converstion...

But the good thing is now, you could merge that first part of my changes in [PR](https://github.com/eclipse/microprofile-telemetry/pull/60) and than I can do a new one (deleting or updating this one) on that state from main branch then.

**Comment by JanWesterkamp-iJUG** [comment]
@brunobat I updated the name of the PR to it's (future) content and will now revert it to the state before the TCK was changed, so I can redo this part.

This JanWesterkamp-iJUG:otel-java-version-update-2 branch is based on the JanWesterkamp-iJUG:otel-spec-version-update-2 branch - so they should fit then, when the last one is merged and I do a rebase on the new main then.

**Review by brunobat — APPROVED** [review]

**Comment by JanWesterkamp-iJUG** [comment]
@brunobat I will close this one now - this prevents git garbage to pile up - I will push the changs to the original https://github.com/eclipse/microprofile-telemetry/pull/60 one.

As this branch is based on the PR of the last one, you can approve the changes there to (they are the same). Additionally the new commits contain the TCK and first README changes.
A few additional will follow and will be part of that original PR or create a new one, when you merged already.

**Pull request closed without merging**
