### PR TITLE
Arquillian version updated

### PR DESCRIPTION
**Pull request by JanWesterkamp-iJUG**
PR for a MP Telemetry Tracing TCK local Arquillian update to 1.7.0.Alpha12.

Alternatively the update can be done in the microprofile-parent project ([PR is available](https://github.com/eclipse/microprofile-parent/pull/67)), but this would require a new release there and then updating the mircroprofile-tck-bom version here.

This PR is intended to fix TCK issues https://github.com/eclipse/microprofile-telemetry/issues/58 and https://github.com/eclipse/microprofile-telemetry/issues/53.

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
Yasmin is trying to execute the tests to find out whether the tests can be executed.

**Review by radcortez — CHANGES_REQUESTED** [review]
Please, do not update individual versions of dependencies. This defeats the entire purpose of the BOM.

The BOM includes TestNG `7.4`, but Arquillian uses `7.5`: https://github.com/arquillian/arquillian-core/blob/1.7.0.Alpha12/build/pom.xml#L31

These need to be in-sync or it can cause issues when running the TCK.

**Comment by JanWesterkamp-iJUG** [comment]
@radcortez this was intended to fix potential errors in the mentioned issue temporary - we can skip this here and do it on the microprofile-parent/tck-bom with aligned versions, if you like.

**Comment by Emily-Jiang** [comment]
I think this PR should be marked as Experimental to avoid confusion. Let's close this one.

**Pull request closed without merging**
